//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSitesiMVC_Proje_YaseminGoktas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZiyaretciIPLog
    {
        public string IPAddress { get; set; }
        public System.DateTime Tarih { get; set; }
    }
}
